package org.deus_ex_java.util;


import org.deus_ex_java.lang.ClassesOps;
import org.deus_ex_java.lang.ParametersValidationException;
import org.deus_ex_java.lang.refined.NonEmptyLowerCaseString;
import org.jspecify.annotations.NullMarked;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static java.util.Map.Entry;
import static java.util.Map.entry;

/**
 * An {@link EnumAndIdsOps} is a thread-safe immutable non-{@code null} utility class that produces a system-wide
 * singleton for augmenting an {@link Enum}'s mutable {@code values()} array by wrapping it in an unmodifiable
 * {@link List}, and providing an associated ID for each enum value.
 * <p>
 * A precondition for using the {@link EnumAndIdsOps} factory methods is:
 * <ul>
 *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique
 *   after being shifted to lower case. If this precondition fails, the factory will throw an
 *   {@link ParametersValidationException} detailing each of the search term collisions.</li>
 * </ul>
 * <p>
 * It also produces an internal cache for enabling a fast O(1) case-insensitive name search for a specific {@link Enum}
 * or ID value (as opposed to the slower O(n) common pattern scanning through the mutable {@code values()} array). In
 * addition, an alternate String may also be associated to each enum value to ease decoding from external sources.
 * <p>
 * The {@link EnumAndIdsOps} class may be added as a property directly to a newly defined {@link Enum}. And/or, it can be
 * used to wrap a pre-existing {@link Enum} which is unable to be directly enhanced/modified (for example, it is part of
 * a vendor SDK).
 * <p>
 * Both approaches, embedded or wrapping, provide all the same functionality, augmentation, and enhancement. And because
 * it is a system-wide singleton, implementing both will result in the exact same instance being returned for both
 * regardless of context.
 * <p>
 * <b>WARNING:</b>
 * <p>
 * The first caller to any of the {@link #from} or {@link #fromAndIsCaching} methods will cache that particular instance
 * which permanently records and caches the conversion functions for both the ID and the lookup Strings. This means any
 * further calls to the {@link #from} or {@link #fromAndIsCaching} methods will always return the originally cached
 * instance, <u>EVEN IF THE CALL PROVIDES DIFFERENT ID AND STRING LOOKUP FUNCTIONS</u>.
 * <p>
 * This is why a {@link #fromAndIsCaching} methods is provided for each {@link #from} method. This enables detecting if
 * the call's functions for both the ID and lookup Strings were recorded.
 * <p>
 * Due to this functions recording restriction, it is recommended a {@link #from} method is used to generate the
 * system-wide singleton in an appropriate place. And that all other calls to obtain the instance either use the
 * provided system-wide singleton, or utilize the {@link #fromCacheOnly(Class)} or {@link #fromCacheOnly(Class, Class)}
 * method.
 *
 * @param <E>  the type of the {@link Enum} values being enhanced
 * @param <ID> type of each {@link Enum} value's associated {@code ID}
 */
@NullMarked
public final class EnumAndIdsOps<E extends Enum<E>, ID> {

  private record ExtendedContext<E extends Enum<E>, ID>(
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString,
      Optional<Function<Entry<E, ID>, Set<NonEmptyLowerCaseString>>> optionalFEAndIdToNonEmptyLowerCaseStrings
  ) {
  }

  private static final Object EXTENDED_CONTEXT_BY_CLASS_E_LOCK = new Object();
  private static final Map<Class<?>, ExtendedContext<?, ?>> EXTENDED_CONTEXT_BY_CLASS_E = new ConcurrentHashMap<>();
  private static final ClassValue<EnumAndIdsOps<?, ?>> ENUM_AND_IDS_OPS_CLASS_VALUE_CACHE = new ClassValue<>() {
    @Override
    protected EnumAndIdsOps<?, ?> computeValue(Class<?> classE) {
      if (!classE.isEnum()) {

        throw new IllegalArgumentException("classE [%s] must be an enum".formatted(classE.getName()));
      }
      var extendedContext = Optional.ofNullable(EXTENDED_CONTEXT_BY_CLASS_E.get(classE))
          .orElseThrow(() ->
              new IllegalStateException("EXTENDED_CONTEXT_BY_CLASS_E did not contain key [%s]".formatted(
                  classE.getName())));

      //noinspection rawtypes,unchecked
      return new EnumAndIdsOps(
          classE,
          extendedContext);
    }
  };

  /**
   * Returns an {@link Optional} containing the cached {@link EnumAndIdsOps} instance already associated with
   * {@code classE}, otherwise {@link Optional#empty}.
   *
   * @param classE the {@link Class} of the specific {@link Enum} that has already being augmented
   * @param <E>    the type of the {@link Enum} values being enhanced
   * @param <ID>   type of each {@link Enum} value's associated {@code ID}
   * @return an {@link Optional} containing the cached {@link EnumAndIdsOps} instance already associated with
   *     {@code classE}, otherwise {@link Optional#empty}
   */
  @SuppressWarnings("unchecked")
  public static <E extends Enum<E>, ID> Optional<EnumAndIdsOps<E, ID>> fromCacheOnly(
      Class<E> classE
  ) {
    return TryCatchesOps.wrap(
            () ->
                ENUM_AND_IDS_OPS_CLASS_VALUE_CACHE.get(classE),
            IllegalStateException.class)
        .map(enumAndIdsOps ->
            (EnumAndIdsOps<E, ID>) enumAndIdsOps)
        .toOptional();
  }

  /**
   * Returns an {@link Optional} containing the cached {@link EnumAndIdsOps} instance already associated with
   * {@code classE} and {@code classId}, otherwise {@link Optional#empty}.
   * <p>
   * This method is distinct from the {@link #fromCacheOnly(Class)} method in that it verifies the found enum has
   * exactly the same {@link Class}
   *
   * @param classE  the {@link Class} of the specific {@link Enum} that has already being augmented
   * @param classId the {@link Class} of the specific {@link ID} that has already being augmented
   * @param <E>     the type of the {@link Enum} values being enhanced
   * @param <ID>    type of each {@link Enum} value's associated {@code ID}
   * @return an {@link Optional} containing the cached {@link EnumAndIdsOps} instance already associated with
   *     {@code classE} and {@code classId}, otherwise {@link Optional#empty}
   */
  @SuppressWarnings("unchecked")
  public static <E extends Enum<E>, ID> Optional<EnumAndIdsOps<E, ID>> fromCacheOnly(
      Class<E> classE,
      Class<ID> classId
  ) {
    return fromCacheOnly(classE)
        .filter(enumAndIdsOps ->
            enumAndIdsOps.getClassId().equals(classId))
        .map(enumAndIdsOpsCaptures ->
            ((EnumAndIdsOps<E, ID>) enumAndIdsOpsCaptures));
  }

  /**
   * A record capturing the details of whether the returned EnumAndIdOps had already been cached by another prior call
   * to any of the {@link #from} or {@link #fromAndIsCaching} methods.
   *
   * @param enumAndIdsOps the <i>singleton</i> associated with the provided {@link Enum}'s class
   * @param isCaching     is {@code true} when this call created the cached instance, otherwise is {@code false} because
   *                      some prior call had already created it
   * @param <E>           the type of the {@link Enum} values being enhanced
   * @param <ID>          type of each {@link Enum} value's associated {@code ID}
   */
  public record EnumAndIdsOpsAndIsCaching<E extends Enum<E>, ID>(
      EnumAndIdsOps<E, ID> enumAndIdsOps,
      boolean isCaching
  ) {

  }

  /**
   * Returns an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using
   * {@link Enum#ordinal()} for the associated {@code ID}.
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE the {@link Class} of the specific enum being augmented
   * @param <E>    the specific Enum's type
   * @return an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class
   */
  public static <E extends Enum<E>> EnumAndIdsOps<E, Integer> from(
      Class<E> classE
  ) {
    return fromAndIsCaching(classE)
        .enumAndIdsOps();
  }

  /**
   * Returns an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   * {@link Enum}'s class using {@link Enum#ordinal()} for the associated {@code ID}, and whether it was cached by this
   * specific call, or cached by some prior call to a {@link #from} or {@link #fromAndIsCaching} method.
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE the {@link Class} of the specific enum being augmented
   * @param <E>    the specific Enum's type
   * @return a {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   *     {@link Enum}'s class using {@link Enum#ordinal()} for the associated {@code ID}, and whether it was cached by
   *     this specific call, or cached by some prior call to a {@link #from} or {@link #fromAndIsCaching} method
   */
  public static <E extends Enum<E>> EnumAndIdsOpsAndIsCaching<E, Integer> fromAndIsCaching(
      Class<E> classE
  ) {
    return fromAndIsCaching(classE, 0);
  }

  /**
   * Returns an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using
   * {@link Enum#ordinal()} plus an offset for the associated {@code ID}.
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE        the {@link Class} of the specific enum being augmented
   * @param ordinalOffset the amount to add to each {@link Enum} value's ordinal before associating the numeric value as
   *                      an {@code ID}
   * @param <E>           the specific Enum's type
   * @return an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class
   */
  public static <E extends Enum<E>> EnumAndIdsOps<E, Integer> from(
      Class<E> classE,
      int ordinalOffset
  ) {
    return fromAndIsCaching(
        classE,
        ordinalOffset)
        .enumAndIdsOps();
  }

  /**
   * Returns an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   * {@link Enum}'s class using {@link Enum#ordinal()} plus an offset for the associated {@code ID}, and whether it was
   * cached by this specific call, or cached by some prior call to a {@link #from} or {@link #fromAndIsCaching} method.
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE        the {@link Class} of the specific enum being augmented
   * @param ordinalOffset the amount to add to each {@link Enum} value's ordinal before associating the numeric value as
   *                      an {@code ID}
   * @param <E>           the specific Enum's type
   * @return an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   *     {@link Enum}'s class using {@link Enum#ordinal()} plus an offset for the associated {@code ID}, and whether it
   *     was cached by this specific call, or cached by some prior call to a {@link #from} or {@link #fromAndIsCaching}
   *     method
   */
  public static <E extends Enum<E>> EnumAndIdsOpsAndIsCaching<E, Integer> fromAndIsCaching(
      Class<E> classE,
      int ordinalOffset
  ) {
    return fromAndIsCaching(
        classE,
        enumValue ->
            enumValue.ordinal() + ordinalOffset);
  }

  /**
   * Returns an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   * derive the associated {@code ID} from each {@link Enum} value, and using the {@link Object#toString()} method on
   * the {@code ID} to derive the String search term for each {@code ID}.
   * <p>
   * A precondition for using this EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique after being shifted to lower case. If this precondition fails, the factory will throw an {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE the {@link Class} of the specific enum being augmented
   * @param fEToId a function to produce an {@code ID} value from an {@link Enum} value
   * @param <E>    the specific Enum's type
   * @param <ID>   type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   *     derive the associated {@code ID} from each {@link Enum} value, using {@code fIdToString} to derive the String
   *     search term for each {@code ID}, and expanding the String search using {@code fEToAltString} to derive an
   *     alternative String from an {@link Enum} value
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOps<E, ID> from(
      Class<E> classE,
      Function<E, ID> fEToId
  ) {
    return fromAndIsCaching(
        classE,
        fEToId)
        .enumAndIdsOps();
  }

  /**
   * Returns an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   * {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value, then
   * using the {@link Object#toString()} method on the {@code ID} to derive the String search term for each {@code ID},
   * and whether it was cached by this specific call, or cached by some prior call to a {@link #from} or
   * {@link #fromAndIsCaching} method.
   * <p>
   * A precondition for using this EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique after being shifted to lower case. If this precondition fails, the factory will throw an {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE the {@link Class} of the specific enum being augmented
   * @param fEToId a function to produce an {@code ID} value from an {@link Enum} value
   * @param <E>    the specific Enum's type
   * @param <ID>   type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   *     {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value,
   *     then using the {@link Object#toString()} method on the {@code ID} to derive the String search term for each
   *     {@code ID}, and whether it was cached by this specific call, or cached by some prior call to a {@link #from} or
   *     {@link #fromAndIsCaching} method
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOpsAndIsCaching<E, ID> fromAndIsCaching(
      Class<E> classE,
      Function<E, ID> fEToId
  ) {
    return fromAndIsCaching(
        classE,
        fEToId,
        enumValueAndId ->
            new NonEmptyLowerCaseString(enumValueAndId.getValue().toString()));
  }

  /**
   * Returns an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   * derive the associated {@code ID} from each {@link Enum} value, and using {@code fEAndIdToNonEmptyLowerCaseString}
   * to derive the String search term for each {@code ID} associated with an Enum value.
   * <p>
   * A precondition for using the EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique after being shifted to lower case. If this precondition fails, the factory will throw an {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE                           the {@link Class} of the specific enum being augmented
   * @param fEToId                           a function to produce an {@code ID} value from an {@link Enum} value
   * @param fEAndIdToNonEmptyLowerCaseString a function to produce a String value for an ID, assuming the returned value
   *                                         is different from that returned by the .toString() method
   * @param <E>                              the specific Enum's type
   * @param <ID>                             type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   *     derive the associated {@code ID} from each {@link Enum} value, and using
   *     {@code fEAndIdToNonEmptyLowerCaseString} to derive the String search term for each {@code ID} associated with
   *     an Enum value
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOps<E, ID> from(
      Class<E> classE,
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString
  ) {
    return fromAndIsCaching(
        classE,
        fEToId,
        fEAndIdToNonEmptyLowerCaseString)
        .enumAndIdsOps();
  }

  /**
   * Returns an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   * {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value, and
   * using {@code fEAndIdToNonEmptyLowerCaseString} to derive the String search term for each {@code ID} associated with
   * an Enum value, and whether it was cached by this specific call, or cached by some prior call to a {@link #from} or
   * {@link #fromAndIsCaching} method.
   * <p>
   * A precondition for using this EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be
   *   unique after being shifted to lower case. If this precondition fails, the factory will throw an
   *   {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE                           the {@link Class} of the specific enum being augmented
   * @param fEToId                           a function to produce an {@code ID} value from an {@link Enum} value
   * @param fEAndIdToNonEmptyLowerCaseString a function to produce a String value for an ID, assuming the returned value
   *                                         is different from that returned by the .toString() method
   * @param <E>                              the specific Enum's type
   * @param <ID>                             type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   *     {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value, and
   *     using {@code fEAndIdToNonEmptyLowerCaseString} to derive the String search term for each {@code ID} associated
   *     with an Enum value, and whether it was cached by this specific call, or cached by some prior call to a
   *     {@link #from} or {@link #fromAndIsCaching} method
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOpsAndIsCaching<E, ID> fromAndIsCaching(
      Class<E> classE,
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString
  ) {
    return fromHelperAndIsCaching(
        classE,
        fEToId,
        fEAndIdToNonEmptyLowerCaseString,
        Optional.empty());
  }

  /**
   * Returns an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   * derive the associated {@code ID} from each {@link Enum} value, using {@code fEAndIdToNonEmptyLowerCaseString} to
   * derive the String search term for each {@code ID}, and expanding the String search terms by using
   * {@code fEAndIdToNonEmptyLowerCaseStrings} to derive alternative String value(s).
   * <p>
   * A precondition for using this EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique after being shifted to lower case. If this precondition fails, the factory will throw an {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE                            the {@link Class} of the specific enum being augmented
   * @param fEToId                            a function to produce an {@code ID} value from an {@link Enum} value
   * @param fEAndIdToNonEmptyLowerCaseString  a function to produce a String value for an ID, assuming the returned
   *                                          values is different from that returned by the .toString() method
   * @param fEAndIdToNonEmptyLowerCaseStrings a function to produce additional String values (0 to n) for an Enum value
   * @param <E>                               the specific Enum's type
   * @param <ID>                              type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOps} <i>singleton</i> for the provided {@link Enum}'s class using {@code fEToId} to
   *     derive the associated {@code ID} from each {@link Enum} value, using {@code fIdToString} to derive the String
   *     search term for each {@code ID}, and expanding the String search using {@code fEToAltString} to derive an
   *     alternative String from an {@link Enum} value
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOps<E, ID> from(
      Class<E> classE,
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString,
      Function<Entry<E, ID>, Set<NonEmptyLowerCaseString>> fEAndIdToNonEmptyLowerCaseStrings
  ) {
    return fromAndIsCaching(
        classE,
        fEToId,
        fEAndIdToNonEmptyLowerCaseString,
        fEAndIdToNonEmptyLowerCaseStrings)
        .enumAndIdsOps();
  }

  /**
   * Returns an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   * {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value, using
   * {@code fEAndIdToNonEmptyLowerCaseString} to derive the String search term for each {@code ID} associated with an
   * Enum value, and expanding the String search terms by using {@code fEAndIdToNonEmptyLowerCaseStrings} to derive
   * alternative String value(s), and whether it was cached by this specific call, or cached by some prior call to a
   * {@link #from} or {@link #fromAndIsCaching} method.
   * <p>
   * A precondition for using this EnumAndIdsOps factory methods is:
   * <ul>
   *   <li>For all the String search terms generated by the factory for a specific {@link Enum}, the terms must be unique after being shifted to lower case. If this precondition fails, the factory will throw an {@link ParametersValidationException} detailing each of the search term collisions.</li>
   * </ul>
   * <p>
   * Rather than reproduce the implementation, a property is used to delegate to {@link EnumsOps} much of the basic
   * {@link Enum} behaviors. This implementation references and reuses the {@link EnumsOps} singleton to augment with
   * the {@code ID} associations.
   * <p>
   * Due to use of a thread-safe internal cache, upon the first call to this factory method with a specific {@link Enum}
   * class, an instance of {@link EnumAndIdsOps} will be generated stored within the internal cache. All future calls to
   * this factory method specifying the same {@link Enum} class (at least within the same {@link ClassLoader}) will
   * ensure the same {@link EnumAndIdsOps} instance is returned. There are no means provided to allow additional
   * independent instances of {@link EnumAndIdsOps} for the same {@link Enum} class.
   *
   * @param classE                            the {@link Class} of the specific enum being augmented
   * @param fEToId                            a function to produce an {@code ID} value from an {@link Enum} value
   * @param fEAndIdToNonEmptyLowerCaseString  a function to produce a String value for an ID, assuming the returned
   *                                          values is different from that returned by the .toString() method
   * @param fEAndIdToNonEmptyLowerCaseStrings a function to produce additional String values (0 to n) for an Enum value
   * @param <E>                               the specific Enum's type
   * @param <ID>                              type of each id associated with an enum's value
   * @return an {@link EnumAndIdsOpsAndIsCaching} containing an {@link EnumAndIdsOps} <i>singleton</i> for the provided
   *     {@link Enum}'s class using {@code fEToId} to derive the associated {@code ID} from each {@link Enum} value,
   *     using {@code fEAndIdToNonEmptyLowerCaseString} to derive the String search term for each {@code ID} associated
   *     with an Enum value, and expanding the String search terms by using {@code fEAndIdToNonEmptyLowerCaseStrings} to
   *     derive alternative String value(s), and whether it was cached by this specific call, or cached by some prior
   *     call to a {@link #from} or {@link #fromAndIsCaching} method
   */
  public static <E extends Enum<E>, ID> EnumAndIdsOpsAndIsCaching<E, ID> fromAndIsCaching(
      Class<E> classE,
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString,
      Function<Entry<E, ID>, Set<NonEmptyLowerCaseString>> fEAndIdToNonEmptyLowerCaseStrings
  ) {
    return fromHelperAndIsCaching(
        classE,
        fEToId,
        fEAndIdToNonEmptyLowerCaseString,
        Optional.of(fEAndIdToNonEmptyLowerCaseStrings));
  }

  @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
  private static <E extends Enum<E>, ID> EnumAndIdsOpsAndIsCaching<E, ID> fromHelperAndIsCaching(
      Class<E> classE,
      Function<E, ID> fEToId,
      Function<Entry<E, ID>, NonEmptyLowerCaseString> fEAndIdToNonEmptyLowerCaseString,
      Optional<Function<Entry<E, ID>, Set<NonEmptyLowerCaseString>>> optionalFEAndIdToNonEmptyLowerCaseStrings
  ) {
    synchronized (EXTENDED_CONTEXT_BY_CLASS_E_LOCK) {
      var isCaching = EXTENDED_CONTEXT_BY_CLASS_E.get(classE) == null;
      if (isCaching) {
        EXTENDED_CONTEXT_BY_CLASS_E.put(
            classE,
            new ExtendedContext<>(
                fEToId,
                fEAndIdToNonEmptyLowerCaseString,
                optionalFEAndIdToNonEmptyLowerCaseStrings));
      }

      //noinspection unchecked
      return new EnumAndIdsOpsAndIsCaching<>(
          (EnumAndIdsOps<E, ID>) ENUM_AND_IDS_OPS_CLASS_VALUE_CACHE.get(classE),
          isCaching);
    }
  }

  private final EnumsOps<E> enumsOps;
  private final Class<ID> classId;
  private final FormatBuilder<E, ID> formatBuilder = FormatBuilder.from(this);
  private final Map<E, ID> orderedMapIdByEnumValue;
  private final Map<ID, E> orderedMapEnumValueById;
  private final Map<String, E> enumValueByNameOrIdOrAlternatesLowerCase;

  private enum CollisionSource {
    ENUM_VALUE,
    ID_VALUE,
    ALTERNATE_STRING_VALUE
  }

  private EnumAndIdsOps(
      Class<E> classE,
      ExtendedContext<E, ID> extendedContext
  ) {
    var fEToId = extendedContext.fEToId();
    var fEAndIdToNonEmptyLowerCaseString =
        extendedContext.fEAndIdToNonEmptyLowerCaseString();
    var optionalFEAndIdToNonEmptyLowerCaseStrings =
        extendedContext.optionalFEAndIdToNonEmptyLowerCaseStrings();
    var enumOps = EnumsOps.from(classE);
    var enumsValues = enumOps.toList();
    var orderedMapIdByEnumValue = MapsOps.toMapOrdered(
        enumsValues.stream(),
        (e) ->
            Optional.of(entry(e, fEToId.apply(e))));
    //validate the .toLowerCase() of...
    //  - enumValue.toString()
    //  - fEAndIdToNonEmptyLowerCaseString.apply(fEToId.apply(enumValue, id))
    //  - optionalFEAndIdToNonEmptyLowerCaseStrings.map(fEAndIdToNonEmptyLowerCaseStrings -> fEAndIdToNonEmptyLowerCaseStrings.apply(enumValue, id)).get()
    //  ...are distinct as all 3 valueOf* methods depend upon this assumption.
    var nameStringAndEnumValueAndCollisionSources = enumsValues
        .stream()
        .map(enumValue ->
            entry(
                enumValue.name().toLowerCase(),
                entry(enumValue, CollisionSource.ENUM_VALUE)))
        .toList();
    var idStringAndEnumValueAndCollisionSources = orderedMapIdByEnumValue
        .entrySet()
        .stream()
        .map(enumValueAndId ->
            entry(
                fEAndIdToNonEmptyLowerCaseString.apply(enumValueAndId).string(),
                entry(enumValueAndId.getKey(), CollisionSource.ID_VALUE)))
        .toList();
    var alternateStringAndEnumValueAndCollisionSources = optionalFEAndIdToNonEmptyLowerCaseStrings
        .map(fEAndIdToNonEmptyLowerCaseStrings ->
            orderedMapIdByEnumValue
                .entrySet()
                .stream()
                .flatMap(enumValueAndId ->
                    fEAndIdToNonEmptyLowerCaseStrings.apply(enumValueAndId)
                        .stream()
                        .map(nonEmptyLowerCaseString ->
                            entry(
                                nonEmptyLowerCaseString.string(),
                                entry(enumValueAndId.getKey(), CollisionSource.ALTERNATE_STRING_VALUE))))
                .toList())
        .orElse(List.of());
    var keyStringAndEnumValueAndCollisionSources =
        Stream.of(
                nameStringAndEnumValueAndCollisionSources.stream(),
                idStringAndEnumValueAndCollisionSources.stream(),
                alternateStringAndEnumValueAndCollisionSources.stream())
            .flatMap(Function.identity())
            .collect(Collectors.groupingBy(Entry::getKey))
            .values()
            .stream()
            .filter(eAsStrings ->
                (eAsStrings.size() > 1) &&
                    //It is acceptable for an enum to have the same resulting String value across
                    //  its name, ID string, and alt strings.
                    //  IOW, this should only return true if the list contains more than one unique
                    //  enum associated with the same string
                    (eAsStrings
                        .stream()
                        .map(entry ->
                            entry.getValue().getKey())
                        .distinct()
                        .count() > 1))
            .flatMap(Collection::stream)
            .toList();
    if (!keyStringAndEnumValueAndCollisionSources.isEmpty()) {
      throw new ParametersValidationException(
          "EnumAndIdsOps invalid parameter(s)",
          "invalid state for enum [%s] where the .toLowerCase() of enumValue.toString(), fEAndIdToNonEmptyLowerCaseString.apply(enumValue, id), and optionalFEAndIdToNonEmptyLowerCaseStrings.map(fEAndIdToNonEmptyLowerCaseStrings -> fEAndIdToNonEmptyLowerCaseStrings.apply(enumValue, id)).get() is not unique across all the enums values - erred values: %s".formatted(
              classE.getSimpleName(),
              String.join(
                  FormatBuilder.DEFAULT_SEPARATOR,
                  keyStringAndEnumValueAndCollisionSources
                      .stream()
                      .sorted(
                          Comparator.<Entry<String, Entry<E, CollisionSource>>, Integer>comparing(
                                  entry ->
                                      entry.getValue().getKey().ordinal())
                              .thenComparing(Entry::getKey))
                      .map(keyLowerCaseAndEnumValueAndCollisionSource -> {
                        var keyLowerCase = keyLowerCaseAndEnumValueAndCollisionSource.getKey();
                        var enumValue = keyLowerCaseAndEnumValueAndCollisionSource.getValue().getKey();
                        var collisionSource = keyLowerCaseAndEnumValueAndCollisionSource.getValue().getValue();

                        return "keyLowerCase: %s -> enumValueName: %s -> collisionSource: %s".formatted(
                            keyLowerCase,
                            enumValue.name(),
                            collisionSource.name());
                      })
                      .toList())));
    }
    var classWildcard = orderedMapIdByEnumValue.values().iterator().next().getClass();
    //noinspection unchecked
    var classId = ClassesOps.narrow(() ->
            (Class<ID>) classWildcard)
        .orElseThrow(() ->
            new IllegalStateException("unable to narrow to Class<ID> for class " + classWildcard.getName()));
    //all preconditions have been validated, so assign the instance fields
    this.enumsOps = enumOps;
    this.classId = classId;
    this.orderedMapIdByEnumValue = orderedMapIdByEnumValue;
    this.orderedMapEnumValueById = MapsOps.swapOrdered(orderedMapIdByEnumValue);
    this.enumValueByNameOrIdOrAlternatesLowerCase = Stream.of(
            nameStringAndEnumValueAndCollisionSources.stream(),
            idStringAndEnumValueAndCollisionSources.stream(),
            alternateStringAndEnumValueAndCollisionSources.stream())
        .flatMap(Function.identity())
        .map(keyLowerCaseAndEnumValueAndCollisionSource ->
            entry(
                keyLowerCaseAndEnumValueAndCollisionSource.getKey(),
                keyLowerCaseAndEnumValueAndCollisionSource.getValue().getKey()))
        .collect(Collectors.toMap(
            Entry::getKey,
            Entry::getValue,
            (stringAndEnumOld, stringAndEnumNew) ->
                //ignoring new entry as it was already resolved to be acceptable in precondition
                //  logic above
                stringAndEnumOld));
  }

  /**
   * Returns an {@link EnumsOps} <i>singleton</i> for the provided {@link Enum}'s class used to delegate base
   * behaviors.
   *
   * @return an {@link EnumsOps} <i>singleton</i> for the provided {@link Enum}'s class used to delegate base behaviors
   */
  public EnumsOps<E> getEnumsOps() {
    return this.enumsOps;
  }

  /**
   * Returns the {@link Class} of the id being associated with the enum.
   *
   * @return the {@link Class} of the id being associated with the enum
   */
  public Class<ID> getClassId() {
    return this.classId;
  }

  /**
   * Returns an unmodifiable {@link List} of each of the {@link Enum}s with its associated ID.
   *
   * @return an unmodifiable {@link List} of each of the {@link Enum}s with its associated ID
   */
  public List<Entry<E, ID>> toList() {
    return getOrderedMapIdByEnumValue()
        .entrySet()
        .stream()
        .toList();
  }

  /**
   * Returns a {@link Stream} of each of the {@link Enum}s with its associated {@code ID}.
   *
   * @return a {@link Stream} of each of the {@link Enum}s with its associated {@code ID}
   */
  public Stream<Entry<E, ID>> stream() {
    return getOrderedMapIdByEnumValue()
        .entrySet()
        .stream();
  }

  /**
   * Returns an unmodifiable <u><i>ordered</i></u> map of each {@link Enum}'s value and its associated {@code ID}, with
   * the {@link Map#keySet()} ordered by the {@link Enum#ordinal()}.
   *
   * @return an unmodifiable <u><i>ordered</i></u> map of each {@link Enum}'s value and its associated {@code ID}, with
   *     the {@link Map#keySet()} ordered by the {@link Enum#ordinal()}
   */
  public Map<E, ID> getOrderedMapIdByEnumValue() {
    return this.orderedMapIdByEnumValue;
  }

  /**
   * Returns the {@code ID} associated with an {@link Enum}'s value.
   *
   * @param enumValue the value upon which to search
   * @return the {@code ID} associated with an {@link Enum}'s value
   */
  public ID get(E enumValue) {
    return getOrderedMapIdByEnumValue().get(enumValue);
  }

  /**
   * Returns an unmodifiable <u><i>ordered</i></u> map of each {@code ID} and it associated {@link Enum}'s value, with
   * the {@link Map#keySet()} ordered by the {@link Enum#ordinal()}.
   *
   * @return an unmodifiable <u><i>ordered</i></u> map of each {@code ID} and it associated {@link Enum}'s value, with
   *     the {@link Map#keySet()} ordered by the {@link Enum#ordinal()}
   */
  public Map<ID, E> getOrderedMapEnumValueById() {
    return this.orderedMapEnumValueById;
  }

  /**
   * Returns an unmodifiable <u><i>ordered</i></u> {@link Set} of all the lower-case String values upon which the
   * {@code valueOf*()} methods perform their {@link String} key lookups.
   *
   * @return an unmodifiable <u><i>ordered</i></u> {@link Set} of all the lower-case String values upon which the
   *     {@code valueOf*()} methods perform their {@link String} key lookups
   */
  public Set<String> valueOfLookupKeys() {
    return SetsOps.toSetOrdered(
        this.enumValueByNameOrIdOrAlternatesLowerCase.keySet()
            .stream()
            .sorted());
  }

  /**
   * Returns the {@link Enum}'s value associated with an {@code ID}.
   *
   * @param id the value upon which to search
   * @return the {@link Enum}'s value associated with an {@code ID}
   */
  public Optional<E> get(ID id) {
    return Optional.ofNullable(getOrderedMapEnumValueById().get(id));
  }

  /**
   * Returns an {@link Optional} containing a {@link Entry} which contains the {@link Enum}'s value and its associated
   * {@code ID} when the lower case of {@code nameOrIdOrAltToString} is found, otherwise an {@link Entry} containing the
   * first {@link Enum} and its associated {@code ID}.
   *
   * @param nameOrIdOrAltToString the case-insensitive term with which the search is performed
   * @return an {@link Optional} containing a {@link Entry} which contains the {@link Enum}'s value and its associated
   *     {@code ID} when the lower case of {@code nameOrIdOrAltToString} is found, otherwise an {@link Entry} containing
   *     the first {@link Enum} and its associated {@code ID}
   */
  public Entry<E, ID> valueOfOrDefaultToFirst(
      String nameOrIdOrAltToString
  ) {
    return valueOf(nameOrIdOrAltToString)
        .orElseGet(() ->
            this.orderedMapIdByEnumValue.entrySet().iterator().next());
  }

  /**
   * Returns an {@link Optional} containing a {@link Entry} which contains the {@link Enum}'s value and its associated
   * {@code ID} when the lower case of {@code nameOrIdOrAltToString} is found, otherwise {@link Optional#empty}.
   *
   * @param nameOrIdOrAlternate the case-insensitive term with which the search is performed
   * @return an {@link Optional} containing a {@link Entry} which contains the {@link Enum}'s value and its associated
   *     {@code ID} when the lower case of {@code nameOrIdOrAltToString} is found, otherwise {@link Optional#empty}
   */
  public Optional<Entry<E, ID>> valueOf(
      String nameOrIdOrAlternate
  ) {
    return Optional.ofNullable(this.enumValueByNameOrIdOrAlternatesLowerCase.get(nameOrIdOrAlternate.toLowerCase()))
        .map(enumValue ->
            entry(
                enumValue,
                getOrderedMapIdByEnumValue().get(enumValue)));
  }

  /**
   * Returns a {@link FormatBuilder} with defaults to assist with String encodings of this collection.
   *
   * @return a {@link FormatBuilder} to assist with String encodings of this collection
   */
  public FormatBuilder<E, ID> getFormatBuilder() {
    return this.formatBuilder;
  }

  /**
   * Defines a format builder to assist with String encodings of this collection.
   *
   * @param <E>  the type of the {@link Enum} values being enhanced
   * @param <ID> type of each {@link Enum} value's associated {@code ID}
   */
  public static class FormatBuilder<E extends Enum<E>, ID> {
    public static final String DEFAULT_SEPARATOR = EnumsOps.FormatBuilder.DEFAULT_SEPARATOR;

    private final EnumAndIdsOps<E, ID> enumAndIdsOps;
    private final Predicate<Entry<E, ID>> filter;
    private final Comparator<Entry<E, ID>> sortStrategy;
    private final Function<Entry<E, ID>, String> reformat;
    private final String separator;

    private FormatBuilder(
        EnumAndIdsOps<E, ID> enumAndIdsOps,
        Predicate<Entry<E, ID>> filter,
        Comparator<Entry<E, ID>> sortStrategy,
        Function<Entry<E, ID>, String> reformat,
        String separator
    ) {
      this.enumAndIdsOps = enumAndIdsOps;
      this.filter = filter;
      this.sortStrategy = sortStrategy;
      this.reformat = reformat;
      this.separator = separator;
    }

    /**
     * Returns a {@link String} formatted as {@code ENUM_VALUE(ID)} for an {@code enumValueAndId} entry.
     * <p>
     * This method is used as the default for {@link FormatBuilder#reformat FormatBuilder.getReformat()} property.
     *
     * @param enumValueAndId the entry from which to produce a formatted String
     * @param <E>            the type of the {@link Enum} values being enhanced
     * @param <ID>           type of each {@link Enum} value's associated {@code ID}
     * @return a {@link String} formatted as {@code ENUM_VALUE(ID)} for an {@code enumValueAndId} entry
     */
    public static <E extends Enum<E>, ID> String defaultReformat(
        Entry<E, ID> enumValueAndId
    ) {
      return "%s(%s)".formatted(
          enumValueAndId.getKey().name(),
          enumValueAndId.getValue().toString());
    }

    /**
     * Returns a new {@link FormatBuilder} that augments an {@link EnumAndIdsOps}, and provides overridable defaults for
     * each of the {@link FormatBuilder}'s properties.
     * <p>
     * Defaults are:
     * <ul>
     *   <li>includes all the {@link EnumAndIdsOps} entries; i.e., no filtering</li>
     *   <li>sorts by each {@link EnumAndIdsOps} entry's {@code ordinal} property</li>
     *   <li>displays each {@link EnumAndIdsOps} entry with the {@link FormatBuilder#defaultReformat(Entry)} method</li>
     *   <li>separates each {@link EnumAndIdsOps} entry's display value with the {@link FormatBuilder#DEFAULT_SEPARATOR}</li>
     * </ul>
     *
     * @param enumAndIdsOps the {@link EnumAndIdsOps} being augmented
     * @param <E>           the type of the {@link Enum} values being enhanced
     * @param <ID>          type of each {@link Enum} value's associated {@code ID}
     * @return a new {@link FormatBuilder} that augments an {@link EnumAndIdsOps}, and provides overridable defaults for
     *     each of the {@link FormatBuilder}'s properties
     */
    public static <E extends Enum<E>, ID> FormatBuilder<E, ID> from(
        EnumAndIdsOps<E, ID> enumAndIdsOps
    ) {
      return new FormatBuilder<>(
          enumAndIdsOps,
          enumValueAndId ->
              true,
          Comparator.comparingInt(
              (Entry<E, ID> enumValueAndId) ->
                  enumValueAndId.getKey().ordinal()),
          FormatBuilder::defaultReformat,
          DEFAULT_SEPARATOR);
    }

    /**
     * Returns the {@link EnumAndIdsOps} being augmented.
     *
     * @return the {@link EnumAndIdsOps} being augmented
     */
    public EnumAndIdsOps<E, ID> getEnumAndIdsOps() {
      return this.enumAndIdsOps;
    }

    /**
     * Returns the {@code filter} {@link Predicate} property this {@link FormatBuilder} instance is using to
     * include/exclude {@link EnumAndIdsOps} entries.
     * <p>
     * The default {@code filter} {@link Predicate} property includes all the {@link EnumAndIdsOps} entries; i.e., no
     * filtering.
     *
     * @return the {@code filter} {@link Predicate} property this {@link FormatBuilder} instance is using to
     *     include/exclude {@link EnumAndIdsOps} entries
     */
    public Predicate<Entry<E, ID>> getFilter() {
      return this.filter;
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     * to include/exclude {@link EnumAndIdsOps} entries.
     *
     * @param filter a {@link Predicate} property that defines how to include/exclude {@link EnumAndIdsOps} entries
     * @return a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     *     to include/exclude {@link EnumAndIdsOps} entries
     */
    public FormatBuilder<E, ID> setFilter(Predicate<Entry<E, ID>> filter) {
      return new FormatBuilder<>(
          this.enumAndIdsOps,
          filter,
          this.sortStrategy,
          this.reformat,
          this.separator);
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     * to include/exclude entries, each entry composed of an {@link Enum} and {@link ID}, based their presence within a
     * source.
     *
     * @param collection a source that is defensively copied into a {@link Set}, and via the {@link Set#contains}
     *                   method, determines what entries to include/exclude
     * @return a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     *     to include/exclude entries, each entry composed of an {@link Enum} and {@link ID}, based their presence
     *     within a source
     */
    public FormatBuilder<E, ID> setFilter(Collection<Entry<E, ID>> collection) {
      return setFilter(collection.stream());
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     * to include/exclude entries, each entry composed of an {@link Enum} and {@link ID}, based their presence within a
     * source.
     *
     * @param stream a source that is defensively copied into a {@link Set}, and via the {@link Set#contains} method,
     *               determines what entries to include/exclude
     * @return a copy of the {@link FormatBuilder} with the {@code filter} {@link Predicate} property that defines how
     *     to include/exclude entries, each entry composed of an {@link Enum} and {@link ID}, based their presence
     *     within a source
     */
    public FormatBuilder<E, ID> setFilter(Stream<Entry<E, ID>> stream) {
      var defensiveCopy = stream.collect(Collectors.toUnmodifiableSet());

      return setFilter(defensiveCopy::contains);
    }

    /**
     * Returns the {@code sortStrategy} {@link Comparator} property this {@link FormatBuilder} instance is using to
     * reorder the filtered {@link EnumAndIdsOps} entries.
     * <p>
     * The default {@code sortStrategy} {@link Comparator} property sorts by each {@link EnumAndIdsOps} entry's by the
     * {@link Enum#ordinal()} property.
     *
     * @return the {@code sortStrategy} {@link Comparator} property this {@link FormatBuilder} instance is using to
     *     reorder the filtered {@link EnumAndIdsOps} entries
     */
    public Comparator<Entry<E, ID>> getSortStrategy() {
      return this.sortStrategy;
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code sortStrategy} {@link Comparator} property that
     * defines how to reorder the filtered {@link EnumAndIdsOps} entries.
     *
     * @param sortStrategy a {@link Comparator} that defines how to reorder the filtered {@link EnumAndIdsOps} entries
     * @return a copy of the {@link FormatBuilder} with the {@code sortStrategy} {@link Comparator} property that
     *     defines how to reorder the filtered {@link EnumAndIdsOps} entries
     */
    public FormatBuilder<E, ID> setSortStrategy(Comparator<Entry<E, ID>> sortStrategy) {
      return new FormatBuilder<>(
          this.enumAndIdsOps,
          this.filter,
          sortStrategy,
          this.reformat,
          this.separator);
    }

    /**
     * Returns the {@code reformat} {@link Function} property this {@link FormatBuilder} instance is using to display
     * each {@link EnumAndIdsOps} entry.
     * <p>
     * The default {@code reformat} {@link Function} property displays each {@link EnumAndIdsOps} entry with the
     * {@link FormatBuilder#defaultReformat(Entry) FormatBuilder.defaultReformat()} method.
     *
     * @return the {@code reformat} {@link Function} property this {@link FormatBuilder} instance is using to display
     *     each {@link EnumAndIdsOps} entry
     */
    public Function<Entry<E, ID>, String> getReformat() {
      return this.reformat;
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code reformat} {@link Function} property that defines how
     * to display each {@link EnumAndIdsOps} entry.
     *
     * @param reformat a {@link Function} that defines how to display each {@link EnumAndIdsOps} entry
     * @return a copy of the {@link FormatBuilder} with the {@code reformat} {@link Function} property that defines how
     *     to display each {@link EnumAndIdsOps} entry
     */
    public FormatBuilder<E, ID> setReformat(Function<Entry<E, ID>, String> reformat) {
      return new FormatBuilder<>(
          this.enumAndIdsOps,
          this.filter,
          this.sortStrategy,
          reformat,
          this.separator);
    }

    /**
     * Returns the {@code separator} String property this {@link FormatBuilder} instance is using to separate and
     * display the filtered and reordered {@link EnumAndIdsOps} entries.
     * <p>
     * The default {@code separator} String property separates each {@link EnumAndIdsOps} entry's display value with the
     * {@link FormatBuilder#DEFAULT_SEPARATOR}.
     *
     * @return the {@code separator} String property this {@link FormatBuilder} instance is using to separate and *
     *     display the filtered and reordered {@link EnumAndIdsOps} entries
     */
    public String getSeparator() {
      return this.separator;
    }

    /**
     * Returns a copy of the {@link FormatBuilder} with the {@code separator} String property that defines how to
     * separate and display the filtered and reordered {@link EnumAndIdsOps} entries.
     *
     * @param separator a {@link Function} that defines how to separate and display the filtered and reordered
     *                  {@link EnumAndIdsOps} entries
     * @return a copy of the {@link FormatBuilder} with the {@code separator} String property that defines how to
     *     separate and display the filtered and reordered {@link EnumAndIdsOps} entries
     */
    public FormatBuilder<E, ID> setSeparator(String separator) {
      if (!this.separator.equals(separator)) {
        return new FormatBuilder<>(
            this.enumAndIdsOps,
            this.filter,
            this.sortStrategy,
            this.reformat,
            separator);
      }

      return this;
    }

    /**
     * Returns the {@link Stream} used by {@code join} to obtain the filtered and reordered {@link Entry} values.
     *
     * @return the {@link Stream} used by {@code join} to obtain the filtered and reordered {@link Entry} values
     */
    public Stream<Entry<E, ID>> toFilteredAndSorted() {
      return this.getEnumAndIdsOps()
          .stream()
          .filter(this.getFilter())
          .sorted(this.getSortStrategy());
    }

    /**
     * Returns the {@link Stream} used by {@code join} to display the filtered and reordered {@link Entry} values.
     *
     * @return the {@link Stream} used by {@code join} to display the filtered and reordered {@link Entry} values
     */
    public Stream<String> toStrings() {
      return toFilteredAndSorted()
          .map(this.getReformat());
    }

    /**
     * Returns the {@link List} used by {@code join} to display the filtered and reordered {@link Entry} values.
     *
     * @return the {@link List} used by {@code join} to display the filtered and reordered {@link Entry} values
     */
    public List<String> toList() {
      return toStrings().toList();
    }

    /**
     * Returns a new {@code String} composed of copies of the provided {@code Enum}s and {@code ID}s; filtered, sorted,
     * and transformed, and then {@link String#join(CharSequence, Iterable)}ed.
     *
     * @return a new {@code String} composed of copies of the provided {@code Enum}s and {@code ID}s; filtered, sorted,
     *     and transformed, and then {@link String#join(CharSequence, Iterable)}ed
     */
    public String join() {
      return String.join(this.getSeparator(), toList());
    }
  }
}
